#!/bin/bash -e

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

usage() {
  cat <<END
Usage: $progname OPTIONS
  -h            Display this help text
  -i            Interactive mode - show a bash console
  -p            Specify listen port (default is 25565)
  -a            Specify minecraft app name (default is 'default')

${*:-}
END
  exit 1
}

while getopts "hp:ia:" OPTION ; do
  case $OPTION in
    h)
      usage
      ;;
    p)
      port=$OPTARG
      ;;
    i)
      interactive=true
      ;;
    a)
      app_name=$OPTARG
      ;;
    *)
      usage
      ;;
  esac
done

port=${port:-25565}
app_name=${app_name:-default}

backup_folder=$DIR/../backup/$app_name
mkdir -p $backup_folder

if [ $interactive ]; then
  docker run -t -i --memory 3072m --volumes-from minecraft_data_$app_name -v /data -v $backup_folder:/backup -p $port:25565/tcp -p $port:25565/udp minecraft /sbin/my_init --skip-startup-files --quiet -- /bin/bash
else
  docker run -d    --memory 3072m --volumes-from minecraft_data_$app_name -v /data -v $backup_folder:/backup -p $port:25565/tcp -p $port:25565/udp minecraft
fi
